// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Help from '../cli/commands/help.js'
import Join from '../cli/commands/join.js'
import Postinstall from '../cli/commands/postinstall.js'
import Share from '../cli/commands/share.js'
import Stop from '../cli/commands/stop.js'
import Version from '../cli/commands/version.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['help', 'join', 'postinstall', 'share', 'stop', 'version'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'help': Help,
  'join': Join,
  'postinstall': Postinstall,
  'share': Share,
  'stop': Stop,
  'version': Version
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'help': {
      name: 'help',
      description: 'Show help information',
      path: '../cli/commands/help'
    },
  'join': {
      name: 'join',
      description: 'Join a remote development environment',
      path: '../cli/commands/join'
    },
  'postinstall': {
      name: 'postinstall',
      description: 'Run postinstall command',
      path: '../cli/commands/postinstall'
    },
  'share': {
      name: 'share',
      description: 'Share a remote development environment',
      options: {
        'detach': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Run in detached mode', short: 'd', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":341,"end":346,"loc":{"start":{"line":12,"column":33,"index":341},"end":{"line":12,"column":38,"index":346}},"value":false}}]}, validator: '(val) => true' },
        'readonly': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Run in readonly mode', short: 'r', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":470,"end":475,"loc":{"start":{"line":16,"column":33,"index":470},"end":{"line":16,"column":38,"index":475}},"value":false}}]}, validator: '(val) => true' }
      },
      path: '../cli/commands/share'
    },
  'stop': {
      name: 'stop',
      description: 'Stop a remote development environment',
      path: '../cli/commands/stop'
    },
  'version': {
      name: 'version',
      description: 'Show version information',
      path: '../cli/commands/version'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
