// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Join from '../cli/commands/join.js'
import Postinstall from '../cli/commands/postinstall.js'
import Share from '../cli/commands/share.js'
import Status from '../cli/commands/status.js'
import Unshare from '../cli/commands/unshare.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['join', 'postinstall', 'share', 'status', 'unshare'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'join': Join,
  'postinstall': Postinstall,
  'share': Share,
  'status': Status,
  'unshare': Unshare
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'join': {
      name: 'join',
      description: 'Join a remote development environment',
      path: '../cli/commands/join'
    },
  'postinstall': {
      name: 'postinstall',
      description: 'Run postinstall command',
      path: '../cli/commands/postinstall'
    },
  'share': {
      name: 'share',
      description: 'Share a remote development environment',
      path: '../cli/commands/share'
    },
  'status': {
      name: 'status',
      description: 'Check if Delphis is running',
      path: '../cli/commands/status'
    },
  'unshare': {
      name: 'unshare',
      description: 'Unshare your current development environment',
      options: {
        'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Force stop the container', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":526,"end":531,"loc":{"start":{"line":16,"column":33,"index":526},"end":{"line":16,"column":38,"index":531}},"value":false}}]}, validator: '(val) => true' }
      },
      path: '../cli/commands/unshare'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
